### ISSUE TITLE
UART problem with stm branch

### ISSUE THREAD

**Issue by louisom** [beckus/qemu_stm32#15] opened 2016-08-07 02:54 UTC
Hi beckus, 
I just clone qemu_stm32 `stm32` branch and, after make it and `make uart_echo_QEMURUN`, I found that serial0 didn't answer my input anyway.

But, after downloading v0.13, and redo again, uart_echo_QEMURUN works.

I'm wondering why `stm32` branch didn't work, can you give me some clue?

thanks!

p.s. using: gcc6.1, archlinux-x64

**Comment by T0jan** [comment] 2016-10-17 10:49
i can confirm this issue. a fast workaround would be nice!

edit: the error can be found in the stm32_p103.c. There seems to be an error with the multiple UART ports, if you uncomment the other two UART connections, it runs as in v0.13.

I will look further into it and will comment here, if I can set up multiple UART ports correctly.

**Comment by oska874** [comment] 2017-12-13 04:48
You should look at /dev/pts/ twice: first look before running `make`,second look after `make`, then you will find that there have add a file,then you can use `minicom` to read from it:
```
sudo minicom -D /dev/pts/5
```
ps: `5` is the new file in `/dev/pts`.

**Comment by beckus** [comment] 2018-07-25 05:02
I apologize for the very long delay in responding. The problem should be fixed now in commit 415f9ab43431024b9e44a32c2aa8aed9afbc1cb6 .

**Closed as completed by beckus** 2018-07-25 05:02 UTC
